spring.application.name=PromptHub

# データベース接続
# Koyebでは環境変数を使用
# 自分のPCでは「:」の右側の設定を使用
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/prompthub}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# Entityをもとにテーブルを自動作成・更新する
spring.jpa.hibernate.ddl-auto=update

# 実行されたSQLをコンソールに表示する
spring.jpa.show-sql=true

# PostgreSQLを使用する設定
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 公開先から指定されたポートを使う
# 自分のPCでは8080を使う
server.port=${PORT:8080}

