spring.application.name=PromptHub

# PostgreSQLへの接続設定
# Spring Bootからprompthubデータベースを操作できるようにする設定

spring.datasource.url=jdbc:postgresql://localhost:5432/prompthub
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.datasource.password=psql

# JPA設定
# Entityクラスから自動でテーブルを作成・更新する

# 実行されたSQLをコンソールに表示する
spring.jpa.show-sql=true

# PostgreSQL用の設定
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect